README.md
index.js

Fixes #10
A more permanent solution would be for Azure SWA to support Node 14 in managed functions.

Transpile function output for Node 12

---

.vscode/settings.json
index.js
package-lock.json
package.json

Same change as the one to official adapters in https://github.com/sveltejs/kit/pull/3222
Everything in the app directory (i.e. `/_app`) has a filename that includes a hash, and thus can have the immutable cache-control header.
Also bumps SvelteKit peer dependency to next-218, since we need the new `builder.appDir` property.

Add immutable cache headers to hashed assets

---

files/entry.js

When I return a binary response from an endpoint, it is encoded as text by the adapter. This PR fixes that by returning the raw body from SvelteKit's response and setting isRaw in context.res to true. I think changing this for all responses is appropriate, since SvelteKit is already handling encoding for text content types.

Render response as Uint8Array instead of text

---

files/entry.d.ts
files/entry.js
index.js
package-lock.json
package.json

SvelteKit 1.0.0-next.280 introduced a small breaking change for adapters. This PR includes the changes from #32, so I'm going to open it as a draft.

Replace app.render with server.respond

---

index.js

If there are no prerendered pages, the build would throw a file not found error since staticDir is rimraf'ed on line 70. It's an odd corner case but I did end up hitting it.
Thank you for publishing this adapter!

Fixing an issue with missing folder

---

README.md
files/api/package.json
files/entry.js
index.js
package-lock.json
package.json
types/swa.d.ts

Fixes #44
Fixes #45
Fixes #12
This PR handles several recent SvelteKit breaking changes. 
- Target Node 16 using the `apiRuntime` SWA setting. With this change, you now need to have a package.json inside your `api/` directory. Without it, the function app will not build. The adapter will throw an error if this file is not present.
- Use new SvelteKit polyfill package
- Only mark files in `/_app/immutable` as immutable.

Drop Node 14, handle polyfill breaking change, update immutable directory

---

index.js

writeStatic has been removed from the adapter API
See https://github.com/sveltejs/kit/pull/5618
fixes #52

feat: remove call to writeStatic

---

README.md
index.d.ts
index.js

From reading some other issues, it sounds like you may be planning to remove esbuild all together. However, in the meantime, I keep running into scenarios that require some specific esbuild options (such as `external`). This PR allows you to add to the default options:
```
adapter: azure({
esbuildOptions: {
external: [
'pg-native'
]
}
})
```

Add the ability to extend esbuild options

---

files/entry.js
package-lock.json
package.json

Sets env with server.init.
I only increased to the min version to get `server.init` (1.0.0-next.395). However, this seems to be working fine for me with 1.0.0-next.405. Just let me know if you want me to increase the version.
fixes: https://github.com/geoffrich/svelte-adapter-azure-swa/issues/55

feat: sets env with server.init

---

README.md

context option seems to be [deprecated](https://azure.github.io/static-web-apps-cli/docs/cli/swa-config) seems like it was replaced with the outputLocation option. Tested on my environment and it works.

Update example swa-cli.config.json in README

---

CONTRIBUTING.md
README.md
index.js
package-lock.json
package.json
test/index.test.js
test/json.js

Related to #19 
- Add unit testing with Vitest.
- Add Contributing guidelines
- Remove unnecessary files from package

Add unit tests

---

files/entry.js
files/headers.js
package-lock.json
package.json
test/headers.test.js

This fixes #63, according to local tests with the SWA cli. SvelteKit returns cookies combined together in a single header, so they have to be split apart and parsed into a structure SWA/Azure understands. I haven't tested this in Azure, but if it doesn't work there it's because of the problems mentioned here: https://github.com/Azure/static-web-apps/issues/278

Fixes #63 Multiple Set-Cookie not working

---

.github/workflows/azure-static-web-apps-polite-desert-00b80111e.yml
README.md
demo/README.md
demo/src/routes/+page.svelte

Closes #79
Deploy the demo app to Azure SWA. This will help us catch build-related bugs since we'll build the demo app with the local adapter as part of the PR.
The Azure SWA workflow is noisy - it creates a new comment on every push - so I added a job that will remove the bot comments before re-deploying.

Deploy demo to Azure SWA

---

README.md

The symptom is:
> [WARNING] Api Directory Location: 'build/server' could not be found. Azure Functions will not be created.
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored. Copying 'staticwebapp.config.json' to build output Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.

README: Describe situation where the repo root != `app_location`

---

demo/.gitignore
demo/package-lock.json
demo/package.json
demo/src/app.d.ts
demo/src/app.html
demo/src/routes/styles.css
demo/src/routes/sverdle/+page.server.js
demo/src/routes/sverdle/+page.svelte
demo/src/routes/sverdle/game.js
demo/src/routes/sverdle/reduced-motion.js
demo/swa-cli.config.json
package-lock.json
package.json

Closes #98
- bump package dependencies to SvelteKit 1.0
- regenerate demo with latest template and bump to 1.0

feat: bump deps to SvelteKit 1.0

---

README.md

The host option is needed for `swa` to work on systems where `localhost` resolves to the IPv6 loopback address `::1`.  See Azure/static-web-apps-cli#646.

Set `host` in sample `swa-cli.config.json`

---

README.md
demo/package-lock.json
demo/src/app.d.ts
files/entry.js
files/headers.js
index.d.ts
test/headers.test.js
types/swa.d.ts

Please see the commit messages for details.
Not sure how to / if it's possible to automatically have the Platform types
imported in the apps that use this adapter. Workaround is to add this to
the top of `src/app.d.ts`:
/// <reference types="svelte-adapter-azure-swa" />
Other adapters seem to put the types in `ambient.d.ts`, but this doesn't
seem to fix the problem.
Fixes #103.

feat: expose client principal through platform

---

.github/workflows/azure-static-web-apps-polite-desert-00b80111e.yml

This fixes a persistent npm error when running `prepare` in the demo app: 
```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /github/home/.npm/_cacache/index-v5/ca/7e
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:123 "/github/home/.npm"
npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2023-03-11T20_07_27_602Z-debug-0.log
npm ERR! code 243
npm ERR! path /github/workspace/demo
npm ERR! command failed
npm ERR! command sh -c -- cd .. && npm i
npm ERR! A complete log of this run can be found in:
npm ERR! …
```

ci: work around npm cache issue

---

files/entry.js

When the request body contains binary data it gets parsed incorrectly, leading to corrupted data.
According to https://github.com/Azure/azure-functions-nodejs-library/blob/752fd223518fb53c217d5929d5933df0ad061d49/types/http.d.ts#L92-L98 the body property already contains a Buffer for certain media types, so there's no need to create a new one from the rawBody anyway.

fix: binary body is incorrectly parsed as UTF-8

---

files/entry.js

Closes #62 
Alternative to #72
Instead of top-level await, I opted to await before handling any requests. Not sure if Azure functions support top-level await, but either way it's probably best to check right before we need it.
This is similar to the [adapter-vercel](https://github.com/sveltejs/kit/blob/b2dbbdfcb2bf178337080bbe4a964f67b304c2ab/packages/adapter-vercel/files/edge.js#L14) implementation.

fix: await server init

---

README.md
files/entry.js
index.d.ts

Closes #126 
Related #30 
This PR adds the Azure function [context](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node#context-object) to the platform exposed by the adapter.

feat: add context to the platform object

---

README.md

Updated documentation for monorepo support, covering the correct approach based on  issues / problems I ran into initially.

Updated Readme.md for monorepo support

---

README.md
index.d.ts
index.js
test/index.test.js

Closes #89
SWA reserves the `/api` prefix, so any overlapping SvelteKit routes will not be reachable in production and hitting them returns confusing errors (see linked issue and #78 for context).
This PR throws an error if it finds routes beginning with `/api` while building and instructions the user to rename the routes. If you do want to allow these routes for some reason, you can set `allowReservedSwaRoutes` in your adapter options. However, this will _not_ make it so SvelteKit /api routes are accessible in production, since this is an SWA limitation.
Note: this check will only run in SvelteKit 1.5 and later, since it uses a property added in that release.

feat: throw error if /api routes defined

---

README.md
demo/svelte.config.js
index.js
test/index.test.js

Closes #48 
Instead of introducing a separate config option to set a custom node version, this PR allows setting `platform.apiRuntime` via `customStaticWebAppConfig`
e.g.
```js
// svelte.config.js
import adapter from 'svelte-adapter-azure-swa';
/** @type {import('@sveltejs/kit').Config} */
const config = {
kit: {
adapter: adapter({
customStaticWebAppConfig: {
platform: {
apiRuntime: 'node:18'
}
}
})
}
};
export default config;
```

feat: allow overriding `platform.apiRuntime`

---

README.md
index.d.ts
index.js

Hi @geoffrich, thanks for the work you do here. It's a little change, but I hope it's correct. I'm pretty new to SvelteKit, so admittedly I'm not quite sure how I could go about testing this adapter locally. Double whammy, I've also never contributed to anything open source before. If I need to do more, please just let me know and I'll learn and give a go this weekend 🏎️
My use case was mentioned in #148 --this is causing a bug that prevents me from logging entries on my grandma's TV app (that's secretly a SvelteKit website)
Closes #148 
Mentioned in #51 #56

Add keepNames to esbuild options

---

files/headers.js
test/headers.test.js

Related https://github.com/geoffrich/svelte-adapter-azure-swa/issues/157
With this PR, we won't throw if the parsed client principal can't be decoded as JSON. We'll return undefined instead.
The underlying issue linked above still needs to be fixed, however.

fix: do not throw on parsing client principal

---

files/entry.js

Closes https://github.com/geoffrich/svelte-adapter-azure-swa/issues/178
Azure functions seem to strip the content-type header from empty POST requests, but SvelteKit requires it. Add it back before sending the request to SK.
More details: https://github.com/geoffrich/svelte-adapter-azure-swa/issues/178#issuecomment-2212849832

Add missing content-type header for empty POST requests

---

README.md

Documents the behavior encountered in #178 and the workaround in #179.
Per discussion with @geoffrich in https://github.com/geoffrich/svelte-adapter-azure-swa/issues/178#issuecomment-2220309102

Add gotchas section to README
